---
language: python
python:
  - 2.7
  - 3.5
  - 3.6
install:
  - pip install pytest pytest-cov
script:
  - pytest --cov --doctest-modules '--doctest-glob=atdtool/*'
after_success: bash <(curl -s https://codecov.io/bash)
jobs:
  include:
    - env: [ omnilint ]
      language: generic
      install: docker pull lpenz/omnilint
      script: docker run --rm -v "$PWD:$PWD" -e "RWD=$PWD" -e "MY_UID=$UID" lpenz/omnilint
      after_success:
