language: python
python:
  - "2.7"
before_install:
  # coveralls:
  - pip install coveralls
  # static checkers:
  - pip install flake8 py3kwarn
addons:
  apt:
    packages:
      - txt2tags
script:
  - nosetests --with-doc --exe --with-coverage
  - pip install .
  # Test if we .gitignore test files:
  - TMP=$(tempfile)
  - git ls-files . --exclude-standard --others | tee "$TMP"
  - if test -s "$TMP"; then false; else true; fi
  # Test if we .gitignore any tracked files:
  - git ls-files -i --exclude-standard | tee "$TMP"
  - if test -s "$TMP"; then false; else true; fi
  # static checkers:
  - flake8 . bin/*
after_success:
  - coveralls
